import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => { try { const keys = ['data-new-gr-c-s-check-loaded', 'data-gr-ext-installed']; for (const k of keys) { if (document.documentElement && document.documentElement.hasAttribute(k)) document.documentElement.removeAttribute(k); if (document.body && document.body.hasAttribute(k)) document.body.removeAttribute(k); } } catch(e){} })();`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
